### ISSUE TITLE
When using a custom template the `gridItems` are not an array & break the *ngFor directive

### ISSUE THREAD

**Issue by zjkipping** [incrudable/forms#14]
This can be reproduced by using the snippet from the bottom of the readme.

You will get the following error in the console:
![image](https://user-images.githubusercontent.com/16586869/167202019-38f6502c-cd5f-4fd6-acd0-9cdb0bf8e4cf.png)

If you look at the value of the `gridItems` that you are supposed to loop over it's `{ "source": { "source": { "source": { "source": {} } } } }` (based on running it through a ` | json` pipe in the template).

**Comment by dpsthree** [comment]
I'll take a look at the readme, but I assume it is out of date. Until then, you can find a working version of a custom layout here:
https://github.com/incrudable/forms/tree/master/apps/demo/src/app/custom-layout

**Comment by zjkipping** [comment]
Ah, ya based on that template. The `gridItems` is actually an observable. So, there is a need to use ` | async` with it for the `*ngFor`. Will look at updating the readme in a bit.
