### ISSUE TITLE
Casing of the runtime control types is not consistent

### ISSUE THREAD

**Issue by zjkipping** [incrudable/forms#15]
The casing of the various runtime control types hops back and forth between capitalizing the `t` in time and keeping it lowercase. This makes the input property setup of custom control components rather confusing at times.

Types with capital `t` in `time`:
- `InputRunTimeControl`
- `DateRunTimeControl`
- `TimeRunTimeControl`

Types with a lowercase `t` in `time`:
- `SelectRuntimeControl`
- `RadioGroupRuntimeControl`
- `CheckGroupRuntimeControl`

**Comment by dpsthree** [comment]
Good catch, these should all be "Runtime". I'll take a look, but feel free to submit a PR if you get to it first.
