### ISSUE TITLE
address example not accepting user input

### ISSUE THREAD

**Issue by dpsthree** [incrudable/forms#7]
On the built-in example app, on the the address/shipping example...

Users can select a country. This succeeds in populating the list of states that a user can choose. However, when a user chooses a state, it does not populate the input. It should :)

**Comment by zjkipping** [comment]
Hmmm, ya I'll take a look at that. Was focused more on getting the hooks working haha.

**Comment by dpsthree** [comment]
This works now. Likely fixed by @zjkipping some time ago
